#!/system/bin/sh



log_i() {
	echo "[$(date +%T)]: [*] $1" >> "$klog"
	echo "" >> "$klog"
}

log_d() {
	echo "$1" >> "$kdbg"
	echo "$1"
}

log_e() {
	echo "[!] $1" >> "$kdbg"
	echo "[!] $1"
}

write() {
	[[ ! -f "$1" ]] && {
		log_e "$1 doesn't exist, skipping..."
		return 1
	}
	chmod +rw "$1"
	curval=$(cat "$1")
	[[ "$curval" == "$2" ]] && {
		log_d "$1 is already set to $2, skipping..."
		return 0
	}
	! echo -n "$2" > "$1" && {
		log_e "Failed: $1 -> $2"
		return 1
	}
	log_d "$1 $curval -> $2"
}

kill_svc() {
	pkill -SIGTERM "$1"
	pkill -KILL "$1"
	stop "$1"
}

cpuctl="/dev/cpuctl/"
dbg="/sys/kernel/debug/sched_features"
f2fs="/sys/fs/f2fs/"
fs="/proc/sys/fs/"
gpu="/sys/class/kgsl/kgsl-3d0/"
kdbg="/sdcard/aio/aio_dbg.log"
kernel="/proc/sys/kernel/"
klog="/sdcard/aio/aio.log"
lmk="/sys/module/lowmemorykiller/parameters/"
stune="/dev/stune/"
tcp_v4="/proc/sys/net/ipv4/"
vm="/proc/sys/vm/"
cpug="/sys/devices/system/cpu/"

stop_services() {
	services=(
		"aplogd"
		"charge_logger"
		"cnss_diag"
		"dumpstate"
		"idd-logreader"
		"idd-logreadermain"
		"ipacm-diag"
		"logcat"
		"logcatd"
		"logd"
		"mediametrics"
		"ramdump"
		"stats"
		"statscompanion"
		"statsd"
		"subsystem_ramdump"
		"tcpdump"
		"tombstoned"
		"traced"
		"traced_probes"
		"vendor.cnss_diag"
		"vendor.ipacm-diag"
		"vendor.tcpdump"
		"wlan_logging"
	)
	for service in "${services[@]}"; do
    	kill_svc "$service"
	done
	log_i "Disabled few debug services and userspace daemons"
}


write "/sys/class/thermal/thermal_message/sconfig" "10"

boost_tune() {
	[[ -e "/sys/module/cpu_boost/parameters/dynamic_stune_boost" ]] && {
		write "/sys/module/cpu_boost/parameters/dynamic_stune_boost" "0"
		log_i "Disabled dynamic stune boost"
	}
	[[ -d "/sys/module/cpu_boost/" ]] && {
		write "/sys/module/cpu_boost/parameters/input_boost_ms" "0"
		write "/sys/module/cpu_boost/parameters/sched_boost_on_input" "0"
		write "/sys/module/cpu_boost/parameters/sched_boost_on_powerkey_input" "0"
		write "/sys/module/cpu_boost/parameters/powerkey_input_boost_ms" "0"
		log_i "Disabled CAF CPU input boost"
	}
	[[ -d "/sys/module/cpu_input_boost/" ]] && {
		write "/sys/module/cpu_input_boost/parameters/input_boost_duration" "0"
		write "/sys/module/cpu_input_boost/parameters/wake_boost_duration" "0"
		log_i "Disabled CPU input boost"
	}
	write "${kernel}launcher_boost_enabled" "0"
	write "${kernel}slide_boost_enabled" "0"
	write "/sys/devices/system/cpu/sched/sched_boost" "0"
	write "/sys/kernel/tracing/events/sched/sched_boost_cpu" "0"
}

io_tune() {
	for queue in /sys/block/*/queue/; do
		avail_scheds=`cat "${queue}scheduler"`
		for sched in cfq noop kyber bfq mq-deadline none; do
			if [[ "$avail_scheds" == *"$sched"* ]]
			then
				write "${queue}scheduler" "$sched"
				break
			fi
		done
		write "${queue}add_random" "0"
		write "${queue}io_poll" "0"
		write "${queue}iostats" "0"
	done
	for i in ${f2fs}*/; do
		write "${i}iostat_enable" "0"
	done
	log_i "Tweaked I/O scheduler"
}

cpu_tune() {
	for cpu in /sys/devices/system/cpu/cpu*/cpufreq
	do
		avail_govs="$(cat "$cpu/scaling_available_governors")"
		for governor in sugov_ext schedutil
		do
			if [[ "$avail_govs" == *"$governor"* ]]
			then
				write "$cpu/scaling_governor" "$governor"
				write "${cpug}$governor/hispeed_load" "90"
				write "${cpug}$governor/hispeed_freq" "4294967295"
				write "${cpug}$governor/pl" "1"
				write "${cpug}$governor/iowait_boost_enable" "1"
				break
			fi
		done
	done
	[[ -e "/sys/devices/system/cpu/cpuidle/use_deepest_state" ]] && {
		write "/sys/devices/system/cpu/cpuidle/use_deepest_state" "1"
		log_i "Allowed CPUs to use it's deepest sleep state"
	}
}

gpu_tune() {
	write "${gpu}bus_split" "1"
	write "${gpu}devfreq/adrenoboost" "0"
	write "${gpu}force_bus_on" "0"
	write "${gpu}force_clk_on" "0"
	write "${gpu}force_no_nap" "0"
	write "${gpu}force_rail_on" "0"
	write "${gpu}popp" "0"
	write "${gpu}pwrnap" "1"
	write "${gpu}thermal_pwrlevel" "0"
	write "${gpu}throttling" "0"
	write "${gpug}mali_touch_boost_level" "0"
	write "${gpu}boost" "0"
	write "${gpu}cl_boost_disable" "0"
	[[ -d "/sys/module/simple_gpu_algorithm/parameters/" ]] && {
		write "/sys/module/simple_gpu_algorithm/parameters/simple_gpu_activate" "0"
		log_i "Disabled SGPU algorithm"
	}
	[[ -d "/sys/module/adreno_idler/" ]] && {
		write "/sys/module/adreno_idler/parameters/adreno_idler_active" "N"
		log_i "Disabled adreno idler"
	}
	log_i "Tweaked GPU parameters"
}

disable_crypto_tests() {
	[[ -d "/sys/module/cryptomgr/" ]] && {
		write "/sys/module/cryptomgr/parameters/notests" "Y"
		log_i "Disabled forced cryptography tests"
	}
}

schedtune_tune() {
	write "${stune}background/schedtune.boost" "0"
	write "${stune}background/schedtune.prefer_idle" "0"
	write "${stune}background/schedtune.sched_boost" "0"
	write "${stune}camera-daemon/schedtune.boost" "1"
	write "${stune}camera-daemon/schedtune.prefer_idle" "1"
	write "${stune}camera-daemon/schedtune.sched_boost" "0"
	write "${stune}foreground/schedtune.boost" "1"
	write "${stune}foreground/schedtune.prefer_idle" "0"
	write "${stune}foreground/schedtune.sched_boost" "0"
	write "${stune}rt/schedtune.boost" "0"
	write "${stune}rt/schedtune.prefer_idle" "0"
	write "${stune}rt/schedtune.sched_boost" "0"
	write "${stune}schedtune.boost" "0"
	write "${stune}schedtune.prefer_idle" "0"
	write "${stune}schedtune.sched_boost" "0"
	write "${stune}top-app/schedtune.boost" "1"
	write "${stune}top-app/schedtune.prefer_idle" "0"
	write "${stune}top-app/schedtune.sched_boost" "0"
	log_i "Tweaked schedtune settings"
}

config_fs() {
	[[ -d "$fs" ]] && {
		write "${fs}dir-notify-enable" "0"
		write "${fs}lease-break-time" "10"
		write "${fs}leases-enable" "1"
		log_i "Tweaked FS"
	}
}

config_dyn_fsync() {
	[[ -d "/sys/kernel/dyn_fsync/" ]] && {
		write "/sys/kernel/dyn_fsync/Dyn_fsync_active" "Y"
		log_i "Enabled dynamic fsync"
	}
}

disable_crc() {
	[[ -d "/sys/module/mmc_core/" ]] && {
		write "/sys/module/mmc_core/parameters/crc" "N"
		write "/sys/module/mmc_core/parameters/removable" "N"
		write "/sys/module/mmc_core/parameters/use_spi_crc" "N"
		log_i "Disabled CRC"
	}
}

sched_tune() {
	write "${kernel}hung_task_timeout_secs" "0"
	write "${kernel}perf_cpu_time_max_percent" "10"
	write "${kernel}printk_devkmsg" "off"
	write "${kernel}sched_autogroup_enabled" "1"
	write "${kernel}sched_boost" "0"
	write "${kernel}sched_boost_top_app" "1"
	write "${kernel}sched_child_runs_first" "0"
	write "${kernel}sched_conservative_pl" "0"
	write "${kernel}sched_cstate_aware" "1"
	write "${kernel}sched_energy_aware" "1"
	write "${kernel}sched_init_task_load" "20"
	write "${kernel}sched_initial_task_util" "0"
	write "${kernel}sched_migration_fixup" "0"
	write "${kernel}sched_min_task_util_for_boost" "0"
	write "${kernel}sched_min_task_util_for_colocation" "0"
	write "${kernel}sched_prefer_sync_wakee_to_waker" "1"
	write "${kernel}sched_schedstats" "0"
	write "${kernel}sched_tunable_scaling" "0"
	write "${kernel}sched_walt_rotate_big_tasks" "1"
	write "${kernel}timer_migration" "1"
	write "/proc/sys/dev/tty/ldisc_autoload" "0"
	write "/sys/devices/system/cpu/cpufreq/hotplug/cpu_hotplug_disable" "1"
	write "/sys/devices/system/cpu/sched/hint_enable" "0"
	write "/sys/kernel/debug/msm_vidc/disable_thermal_mitigation" "0"
	write "/sys/kernel/debug/msm_vidc/fw_low_power_mode" "1"
	log_i "Tweaked various kernel parameters to a better overall performance"
}

fp_boost() {
	[[ -d "/sys/kernel/fp_boost/" ]] && {
		write "/sys/kernel/fp_boost/enabled" "0"
		log_i "Disabled fingerprint boost"
	}
}

vm_lmk_tune() {
	sync
	write "${lmk}enable_adaptive_lmk" "0"
	write "${lmk}lmk_fast_run" "0"
	write "${lmk}oom_reaper" "1"
	write "${vm}block_dump" "0"
	write "${vm}extfrag_threshold" "750"
	write "${vm}laptop_mode" "0"
	write "${vm}oom_dump_tasks" "0"
	write "${vm}overcommit_memory" "1"
	write "${vm}overcommit_ratio" "100"
	write "${vm}page-cluster" "0"
	write "${vm}reap_mem_on_sigkill" "1"
	write "${vm}stat_interval" "600"
	write "/sys/kernel/mm/lru_gen/enabled" "Y"
	write "/sys/kernel/mm/lru_gen/min_ttl_ms" "1000"
	write "/sys/kernel/mm/swap/vma_ra_enabled" "true"
	write "/sys/module/process_reclaim/parameters/enable_process_reclaim" "0"
	log_i "Tweaked various VM and LMK parameters for a improved user-experience"
}

pewq() {
	[[ -e "/sys/module/workqueue/parameters/power_efficient" ]] && {
		write "/sys/module/workqueue/parameters/power_efficient" "Y"
		log_i "Enabled power efficient workqueue"
	}
}

config_tcp() {
	avail_con=`cat "${tcp}tcp_available_congestion_control"`
	for con in bbr2 bbr c2tcp cdg westwood; do
		if [[ "$avail_con" == *"$con"* ]]
		then
			write "${tcp_v4}tcp_congestion_control" "$con"
			break
		fi
	done
	write "${tcp_v4}ip_no_pmtu_disc" "0"
	write "${tcp_v4}tcp_ecn" "1"
	write "${tcp_v4}tcp_fastopen" "3"
	write "${tcp_v4}tcp_mtu_probing" "1"
	#write "${tcp_v4}tcp_no_metrics_save" "1"
	write "${tcp_v4}tcp_sack" "1"
	#write "${tcp_v4}tcp_slow_start_after_idle" "0"
	#write "${tcp_v4}tcp_syncookies" "0"
	#write "${tcp_v4}tcp_timestamps" "0"
	write "${tcp_v4}tcp_tw_recycle" "1"
	write "${tcp_v4}tcp_tw_reuse" "1"
	write "${tcp_v4}tcp_window_scaling" "1"
	#write "/proc/sys/net/core/netdev_max_backlog" "16384"
	#write "/proc/sys/net/core/netdev_tstamp_prequeue" "0"
	log_i "Applied TCP tweaks"
}

kern_pwrsave() {
	[[ -d "/sys/module/battery_saver/" ]] && {
		write "/sys/module/battery_saver/parameters/enabled" "N"
		log_i "Disabled kernel battery saver"
	}
}

pm2_idle_mode() {
	[[ -d "/sys/module/pm2/parameters/" ]] && {
		write "/sys/module/pm2/parameters/idle_sleep_mode" "Y"
		log_i "Enabled pm2 idle sleep mode"
	}
}

enable_usb_fast_chrg() {
	[[ -e "/sys/kernel/fast_charge/force_fast_charge" ]] && {
		write "/sys/kernel/fast_charge/force_fast_charge" "1"
		log_i "Enabled USB 3.0 fast charging"
	}
}

disable_debug() {
	useless=(
		"compat-log"
		"debug_level"
		"debug_mask"
		"debug_mode"
		"edac_mc_log"
		"enable_event_log"
		"enable_ramdumps"
		"log_ce"
		"log_ecn_error"
		"log_enabled"
		"log_level"
		"log_ue"
		"mballoc_debug"
		"seclog"
		"snapshot_crashdumper"
		"tracing_on"
	)
	for keyword in "${useless[@]}"; do
		for file in $(find /sys/ -type f -name "$keyword"); do
			write "$file" "0"
		done
	done
	write "${kernel}compat-log" "0"
	write "${kernel}panic" "0"
	write "${kernel}panic_on_oops" "0"
	write "${kernel}printk" "0 0 0 0"
	write "${kernel}softlockup_panic" "0"
	write "${vm}panic_on_oom" "0"
	write "/proc/sys/debug/exception-trace" "0"
	write "/sys/kernel/debug/debug_enabled" "0"
	write "/sys/kernel/debug/dri/0/debug/enable" "0"
	write "/sys/kernel/debug/rpm_log" "0"
	write "/sys/kernel/debug/sde_rotator0/clk_always_on" "0"
	write "/sys/kernel/debug/sde_rotator0/evtlog/enable" "0"
	write "/sys/kernel/printk_mode/printk_mode" "0"
	write "/sys/module/bluetooth/parameters/disable_ertm" "Y"
	write "/sys/module/bluetooth/parameters/disable_esco" "Y"
	write "/sys/module/dwc3/parameters/ep_addr_rxdbg_mask" "0" 
	write "/sys/module/dwc3/parameters/ep_addr_txdbg_mask" "0"
	write "/sys/module/hid_apple/parameters/fnmode" "0"
	write "/sys/module/hid_magicmouse/parameters/emulate_3button" "N"
	write "/sys/module/hid_magicmouse/parameters/emulate_scroll_wheel" "N"
	write "/sys/module/logger/parameters/log_mode" "2"
	write "/sys/module/mdss_fb/parameters/backlight_dimmer" "N"
	write "/sys/module/otg_wakelock/parameters/enabled" "N" 
	write "/sys/module/printk/parameters/console_suspend" "Y"
	write "/sys/module/service_locator/parameters/enable" "0" 
	write "/sys/module/spurious/parameters/noirqdebug" "Y"
	log_i "Disabled misc debugging"
}

disable_tb() {
	[[ -e "/sys/module/msm_performance/parameters/touchboost" ]] && {
		write "/sys/module/msm_performance/parameters/touchboost" "0"
		log_i "Disabled msm_performance touch boost"
	} || [[ -e "/sys/power/pnpmgr/touch_boost" ]] && {
		write "/sys/power/pnpmgr/long_duration_touch_boost" "0"
		write "/sys/power/pnpmgr/touch_boost" "0"
		log_i "Disabled pnpmgr touch boost"
	}
}

props() {
	resetprop -n arm64.memtag.process.system_server off
	resetprop -n dalvik.vm.dex2oat-minidebuginfo false
	resetprop -n dalvik.vm.minidebuginfo false
	resetprop -n debug.atrace.tags.enableflags 0
	resetprop -n debug.hwui.skia_atrace_enabled false
	resetprop -n debug.mdpcomp.logs 0
	resetprop -n debug.sf.dump 0
	resetprop -n debug.sf.enable_layer_caching true
	resetprop -n debug.sf.enable_small_dirty_detection true
	resetprop -n libc.debug.malloc 0
	resetprop -n media.stagefright.log-uri false
	resetprop -n persist.debug.sf.enable_layer_lifecycle_manager true
	resetprop -n persist.debug.wfd.enable 0
	resetprop -n persist.sys.strictmode.disable 1
	resetprop -n persist.vendor.camera.realtimethread 1
	resetprop -n persist.vendor.radio.adb_log_on 0
	resetprop -n persist.vendor.sys.modem.logging.enable false
	resetprop -n renderthread.skia.reduceopstasksplitting true
	resetprop -n ro.lmk.debug false
	resetprop -n ro.lmk.log_stats false
	resetprop -n ro.surface_flinger.enable_layer_caching true
	resetprop -n sys.wifitracing.started 0

	resetprop -n iorapd.perfetto.enable false
	resetprop -n iorapd.readahead.enable false
	resetprop -n ro.iorapd.enable false
	
	resetprop -n ro.sf.force_hwc_brightness 1
	resetprop -n persist.sys.fuse.passthrough.enable true
	resetprop -n persist.vendor.btstack.enable.lpa true
	resetprop -n ro.surface_flinger.use_content_detection_for_refresh_rate true
	resetprop -n vendor.display.disable_rotator_downscale 1
	
	resetprop -n sys.fflag.override.settings_seamless_transfer true
	resetprop -n vendor.display.enable_optimize_refresh 1
	resetprop -n ro.zygote.disable_gl_preload false
	resetprop -n ro.audio.monitorRotation true

	resetprop -n dalvik.vm.dex2oat64.enabled true
	resetprop -n dalvik.vm.dexopt.secondary true
	resetprop -n pm.dexopt.bg-dexopt everything
	resetprop -n pm.dexopt.cmdline everything
	resetprop -n pm.dexopt.shared everything
	resetprop -n dalvik.vm.systemservercompilerfilter everything
	resetprop -n dalvik.vm.systemuicompilerfilter everything

	resetprop -n vendor.display.enable_async_powermode 1
	resetprop -n vendor.display.enable_inline_writeback 1
	resetprop -n vendor.display.enable_perf_hint_large_comp_cycle 1
	resetprop -n vendor.display.enable_spec_fence 1
	log_i "Applied prop tweaks"
}

cmd_sys() {
	device_config reset untrusted_defaults
	device_config reset untrusted_clear
	device_config reset trusted_defaults
	device_config set_sync_disabled_for_tests until_reboot
	cmd looper_stats disable
	cmd power set-fixed-performance-mode-enabled true
	device_config put activity_manager max_cached_processes 65535
	device_config put activity_manager max_empty_time_millis 43200000
	device_config put activity_manager max_phantom_processes 2147483647
	device_config put activity_manager proactive_kills_enabled false
	device_config put activity_manager use_compaction false
	device_config put activity_manager use_oom_re_ranking true
	device_config put activity_manager uses_weight true
	device_config put activity_manager_native_boot offload_queue_enabled true
	device_config put activity_manager_native_boot use_freezer true
	device_config put interaction_jank_monitor enabled false
	device_config put latency_tracker enabled false
	device_config put media media_metrics_mode 0
	device_config put runtime_native usap_pool_enabled true
	device_config put runtime_native use_app_image_startup_cache true
	device_config put runtime_native_boot disable_lock_profiling true
	device_config put runtime_native_boot enable_generational_cc true
	device_config put runtime_native_boot enable_perfetto false
	device_config put runtime_native_boot enable_readahead false
	device_config put runtime_native_boot enable_uffd_gc_2 true
	device_config put runtime_native_boot iorap_perfetto_enable false
	device_config put runtime_native_boot iorap_readahead_enable false
	device_config put runtime_native_boot is_uffd_gc_enabled true
	device_config put runtime_native_boot pin_camera false
	settings put global activity_starts_logging_enabled 0
	settings put global hotword_detection_enabled 0
	settings put global mobile_data_always_on 0
	settings put global netstats_enabled 0
	settings put global network_recommendations_enabled 0
	#settings put global settings_enable_monitor_phantom_procs false
	settings put secure screensaver_activate_on_dock 0
	settings put secure screensaver_activate_on_sleep 0 
	settings put secure screensaver_enabled 0
	settings put secure send_action_app_error 0
	device_config put netd_native happy_eyeballs_enable true
	device_config put netd_native parallel_lookup true
	device_config put netd_native sort_nameservers true
	log_i "Tweaked system properties"
}

zram_off() {
	swapoff /dev/block/zram0 > /dev/null 2>&1
	write "/sys/block/zram0/disksize" "0"
	write "/sys/block/zram0/reset" "1"
	write "/proc/sys/vm/swappiness" "0"
	log_i "Turned off swap and zram"
}

dexopt() {
	cmd package bg-dexopt-job
	log_i "Background optimization task executed"
}

log_i "Initializing"
init=$(date +%s)
sync

echo "" > "$kdbg"
echo "" > "$klog"
zram_off
disable_crc
disable_crypto_tests
config_fs
config_dyn_fsync
config_tcp
enable_usb_fast_chrg
disable_debug
stop_services
io_tune
boost_tune
cpu_tune
gpu_tune
schedtune_tune
sched_tune
vm_lmk_tune
pewq
disable_tb
fp_boost
pm2_idle_mode
kern_pwrsave
cmd_sys
props
dexopt

log_i "Tweaks applied. Enjoy!"
exit=$(date +%s)
exec_time=$((exit - init))
log_i "Spent time: $exec_time seconds."
