#!/bin/sh

# List of apps to disable.

# --- Analytics & Tracking (Safe to disable) ---
apps="com.miui.analytics com.miui.msa.global com.miui.bugreport com.google.android.feedback com.google.android.apps.wellbeing com.google.android.adservices.api"

# --- Social & Bloatware (Safe to disable) ---
apps="$apps com.facebook.system com.facebook.appmanager com.facebook.services com.microsoft.appmanager com.google.android.videos com.google.android.apps.tachyon"

# --- MIUI Specific Bloat (Mostly safe) ---
apps="$apps com.mi.globalminusscreen com.mi.globalbrowser com.xiaomi.glgm com.xiaomi.payment com.miui.videoplayer com.miui.player com.miui.yellowpage com.miui.touchassistant com.xiaomi.mirror com.milink.service"

# --- Assistant & Hotword (Safe to disable if not using) ---
apps="$apps com.android.hotwordenrollment.xgoogle com.android.hotwordenrollment.okgoogle"

# --- Miscellaneous ---
apps="$apps com.android.traceur com.google.android.apps.restore com.google.android.onetimeinitializer com.google.android.partnersetup com.google.android.apps.subscriptions.red"

# Setup Wizard Safety Check
PROVISIONED=$(getprop device_provisioned)
if [ "$PROVISIONED" = "1" ]; then
    pm disable "com.google.android.setupwizard" > /dev/null 2>&1
fi

# Disable the apps
for app in $apps; do
    pm disable "$app" > /dev/null 2>&1
done
