#!/system/bin/sh



fscc_log="/sdcard/aio/fscc.log"

log_i() {
	echo "[$(date +'%Y-%m-%d %T')]: [*] $1" >"$fscc_log"
	echo "" >> "$fscc_log"
}

pkill -KILL vmtouch

fscc_status() {
	sleep 2
	[[ "$(pgrep -f "vmtouch")" ]] && echo "Running $(cat /proc/meminfo | grep Mlocked | cut -d: -f2 | tr -d ' ') in cache." || echo "Not running."
}

objects=(
	"libc.so" 
	"libm.so" 
	"libdl.so"
	"libdl_android.so"
)
for object in "${objects[@]}"; do
	vmtouch -dLvwf "/apex/com.android.runtime/lib64/bionic/$object"
done

objects=(
	"libc++.so" 
	"libandroid_runtime.so" 
	"libandroid_servers.so" 
	"libgui.so" 
	"libinputflinger.so" 
	"libinputreader.so" 
	"libz.so"
	"libbase.so"
	"libbinder.so"
	"libsync.so"
	"libui.so" 
	"libhwbinder.so"
	"libinput.so"
	"libandroid.so"
	"libandroidfw.so"
	"libhwui.so"
	"libsurfaceflinger.so"
	"libblas.so" 
	"liblzma.so" 
	"ld-android.so"
	"libnetd_client.so"
	"libcutils.so"
	"libutils.so"
	"libsqlite.so"
	"libasyncio.so"
	"libcrypto.so"
	"libhidlbase.so"
	"libmedia.so"
	"libvndksupport.so"
	"libziparchive.so"
	"libnativedisplay.so"
	"libbinder_ndk.so"
	"libcgrouprc.so"
	"libpcre2.so"
	"libprocessgroup.so"
	"libhardware.so"
	"libprotobuf-cpp-lite.so"
	"libprotobuf-cpp-full.so"
	"libnativewindow.so"
	"libvintf.so"
	"libmediautils.so"
	"libsensor.so"
	"liblz4.so"
	"libappfuse.so"
	"libvulkan.so"
	"libcameraservice.so"
)
for object in "${objects[@]}"; do
	vmtouch -dlvwf "/system/lib64/$object"
done

objects=(
	"sensors.ssc.so"
	"libCB.so"
	"libgsl.so"
	"libgui_vendor.so"
	"libgpudataproducer.so"
	"libdpps.so"
	"libadreno_utils.so"
	"libcamxexternalformatutils.so"
	"libipebpsstriping.so"
	"libipebpsstriping170.so"
)
for object in "${objects[@]}"; do
	vmtouch -dlvwf "/vendor/lib64/$object"
done

objects=(
	"app_process64"
	"surfaceflinger"
	"linker64"
)
for object in "${objects[@]}"; do
	vmtouch -dlvwf "/system/bin/$object"
done

vmtouch -dLvwf "$(pm path com.android.systemui | head -1 | cut -d: -f2)"

log_i "FSCC - Filesystem optimizer
Status: $(fscc_status)
"