#!/system/bin/sh



fscc_log="/data/media/0/aio/fscc.log"

log_i() {
	echo "[$(date +'%Y-%m-%d %T')]: [*] $1" >"$fscc_log"
	echo "" >> "$fscc_log"
}

(pkill -KILL vmtouch)

fscc_status() {
	sleep 2
	[[ "$(pgrep -f "vmtouch")" ]] && echo "Running $(cat /proc/meminfo | grep Mlocked | cut -d: -f2 | tr -d ' ') in cache." || echo "Not running."
}

objects=("libc.so" "libm.so" "libdl.so")
lib_paths=("/apex/com.android.runtime/lib/bionic/" "/apex/com.android.runtime/lib64/bionic/")

for object in "${objects[@]}"; do
    for lib_path in "${lib_paths[@]}"; do
        vmtouch -dLtvw "$lib_path$object"
    done
done

objects=("libc++.so" "libandroid_runtime.so" "libandroid_servers.so" "libsurfaceflinger.so" "libgui.so" "libinputflinger.so" "libinputreader.so" "libblas.so" "libpng.so" "libjpeg.so" "liblz4.so" "liblzma.so" "libz.so")
lib_paths=("/system/lib/" "/system/lib64/")

for object in "${objects[@]}"; do
    for lib_path in "${lib_paths[@]}"; do
        vmtouch -dLtvw "$lib_path$object"
    done
done


log_i "FSCC - Filesystem optimizer
Status: $(fscc_status)
"
