#!/system/bin/sh



MODE="speed-profile"
m_log="/sdcard/aio/monolith.log"
package_list=$(pm list packages)

compile_command="pm compile -a"
[ "$1" = "-f" ] && compile_command+=" -f"

echo "$(date '+%Y-%m-%d %H:%M:%S') >>> Compiling packages" >> "$m_log"
$compile_command -m "$MODE"

echo "$(date '+%Y-%m-%d %H:%M:%S') >>> Compiling layouts" >> "$m_log"
$compile_command --compile-layouts

echo "$(date '+%Y-%m-%d %H:%M:%S') >>> Compiling secondary dex files" >> "$m_log"
$compile_command --secondary-dex -m "$MODE" 

echo "$(date '+%Y-%m-%d %H:%M:%S') >>> Reconciling secondary dex files" >> "$m_log"
for package in $package_list; do
    pm reconcile-secondary-dex-files "$package"
done

echo "$(date '+%Y-%m-%d %H:%M:%S') >>> Done" >> "$m_log"
